/**
 *  Copyright 2011 by Benjamin J. Land (a.k.a. BenLand100)
 *
 *  This file is part of the CppCraft.
 *
 *  CppCraft is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  CppCraft is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with CppCraft. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _items
#define _items

#define M_NONE          0
#define M_STONE         1
#define M_DIRT          2
#define M_WOOD          3
#define M_CROPS         4
#define M_WATER         5
#define M_LAVA          6
#define M_SAND          7
#define M_LEAVES        8
#define M_SPONGE        9
#define M_GLASS         10
#define M_WOOL          11
#define M_IRON          12
#define M_TNT           13
#define M_REDSTONE      14
#define M_FIRE          15
#define M_SNOW          16
#define M_ICE           17
#define M_SNOWBLOCK     18
#define M_CACTUS        19
#define M_CLAY          20
#define M_PUMPKIN       21
#define M_PORTAL        22
#define M_CAKE          23
#define M_DIAMOND       24
#define M_GOLD          25

inline const char* item_name(int id) {
    switch(id) {
        case -1: return (const char*)"NoItem";
        case 0: return (const char*)"Air";
        case 1: return (const char*)"Stone";
        case 2: return (const char*)"Grass";
        case 3: return (const char*)"Dirt";
        case 4: return (const char*)"Cobblestone";
        case 5: return (const char*)"WoodenPlank";
        case 6: return (const char*)"Sapling";
        case 7: return (const char*)"Bedrock";
        case 8: return (const char*)"Water";
        case 9: return (const char*)"StationaryWater";
        case 10: return (const char*)"Lava";
        case 11: return (const char*)"StationaryLava";
        case 12: return (const char*)"Sand";
        case 13: return (const char*)"Gravel";
        case 14: return (const char*)"GoldOre";
        case 15: return (const char*)"IronOre";
        case 16: return (const char*)"CoalOre";
        case 17: return (const char*)"Wood";
        case 18: return (const char*)"Leaves";
        case 19: return (const char*)"Sponge";
        case 20: return (const char*)"Glass";
        case 21: return (const char*)"LapisLazuliOre";
        case 22: return (const char*)"LapisLazuliBlock";
        case 23: return (const char*)"Dispenser";
        case 24: return (const char*)"Sandstone";
        case 25: return (const char*)"NoteBlock";
        case 26: return (const char*)"Bed_placed";
        case 27: return (const char*)"PoweredRail";
        case 28: return (const char*)"DetectorRail";
        case 29: return (const char*)"StickyPiston";
        case 30: return (const char*)"Cobweb";
        case 31: return (const char*)"TallGrass";
        case 32: return (const char*)"DeadShrub";
        case 33: return (const char*)"Piston";
        case 34: return (const char*)"PistonHead";
        case 35: return (const char*)"Wool";
        case 37: return (const char*)"YellowFlower";
        case 38: return (const char*)"RedRose";
        case 39: return (const char*)"BrownMushroom";
        case 40: return (const char*)"RedMushroom";
        case 41: return (const char*)"GoldBlock";
        case 42: return (const char*)"IronBlock";
        case 43: return (const char*)"DoubleSlab";
        case 44: return (const char*)"Slab";
        case 45: return (const char*)"Brick";
        case 46: return (const char*)"Tnt";
        case 47: return (const char*)"Bookshelf";
        case 48: return (const char*)"MossStone";
        case 49: return (const char*)"Obsidian";
        case 50: return (const char*)"Torch";
        case 51: return (const char*)"Fire";
        case 52: return (const char*)"MonsterSpawner";
        case 53: return (const char*)"WoodenStairs";
        case 54: return (const char*)"Chest";
        case 55: return (const char*)"RedstoneWire_placed";
        case 56: return (const char*)"DiamondOre";
        case 57: return (const char*)"DiamondBlock";
        case 58: return (const char*)"CraftingTable";
        case 59: return (const char*)"Crops";
        case 60: return (const char*)"Farmland";
        case 61: return (const char*)"Furnace";
        case 62: return (const char*)"BurningFurnace";
        case 63: return (const char*)"SignPost_placed";
        case 64: return (const char*)"WoodenDoor_placed";
        case 65: return (const char*)"Ladder";
        case 66: return (const char*)"MinecartTracks";
        case 67: return (const char*)"CobblestoneStairs";
        case 68: return (const char*)"WallSign_placed";
        case 69: return (const char*)"Lever";
        case 70: return (const char*)"StonePressurePlate";
        case 71: return (const char*)"IronDoor_placed";
        case 72: return (const char*)"WoodenPressurePlate";
        case 73: return (const char*)"RedstoneOre";
        case 74: return (const char*)"GlowingRedstoneOre";
        case 75: return (const char*)"RedstoneTorchOff_placed";
        case 76: return (const char*)"RedstoneTorchOn";
        case 77: return (const char*)"StoneButton";
        case 78: return (const char*)"Snow";
        case 79: return (const char*)"Ice";
        case 80: return (const char*)"SnowBlock";
        case 81: return (const char*)"Cactus";
        case 82: return (const char*)"Clay";
        case 83: return (const char*)"SugarCane_placed";
        case 84: return (const char*)"Jukebox";
        case 85: return (const char*)"Fence";
        case 86: return (const char*)"Pumpkin";
        case 87: return (const char*)"Netherrack";
        case 88: return (const char*)"SoulSand";
        case 89: return (const char*)"Glowstone";
        case 90: return (const char*)"Portal";
        case 91: return (const char*)"JackOLantern";
        case 92: return (const char*)"Cake_placed";
        case 93: return (const char*)"RedstoneRepeaterOff_placed";
        case 94: return (const char*)"RedstoneRepeaterOn_placed";
        case 96: return (const char*)"Trapdoor";
        case 256: return (const char*)"IronShovel";
        case 257: return (const char*)"IronPickaxe";
        case 258: return (const char*)"IronAxe";
        case 259: return (const char*)"FlintAndSteel";
        case 260: return (const char*)"Apple";
        case 261: return (const char*)"Bow";
        case 262: return (const char*)"Arrow";
        case 263: return (const char*)"Coal";
        case 264: return (const char*)"Diamond";
        case 265: return (const char*)"IronIngot";
        case 266: return (const char*)"GoldIngot";
        case 267: return (const char*)"IronSword";
        case 268: return (const char*)"WoodenSword";
        case 269: return (const char*)"WoodenShovel";
        case 270: return (const char*)"WoodenPickaxe";
        case 271: return (const char*)"WoodenAxe";
        case 272: return (const char*)"StoneSword";
        case 273: return (const char*)"StoneShovel";
        case 274: return (const char*)"StonePickaxe";
        case 275: return (const char*)"StoneAxe";
        case 276: return (const char*)"DiamondSword";
        case 277: return (const char*)"DiamondShovel";
        case 278: return (const char*)"DiamondPickaxe";
        case 279: return (const char*)"DiamondAxe";
        case 280: return (const char*)"Stick";
        case 281: return (const char*)"Bowl";
        case 282: return (const char*)"MushroomStew";
        case 283: return (const char*)"GoldSword";
        case 284: return (const char*)"GoldShovel";
        case 285: return (const char*)"GoldPickaxe";
        case 286: return (const char*)"GoldAxe";
        case 287: return (const char*)"String";
        case 288: return (const char*)"Feather";
        case 289: return (const char*)"Gunpowder";
        case 290: return (const char*)"WoodenHoe";
        case 291: return (const char*)"StoneHoe";
        case 292: return (const char*)"IronHoe";
        case 293: return (const char*)"DiamondHoe";
        case 294: return (const char*)"GoldHoe";
        case 295: return (const char*)"Seeds";
        case 296: return (const char*)"Wheat";
        case 297: return (const char*)"Bread";
        case 298: return (const char*)"LeatherHelmet";
        case 299: return (const char*)"LeatherChestplate";
        case 300: return (const char*)"LeatherLeggings";
        case 301: return (const char*)"LeatherBoots";
        case 302: return (const char*)"ChainmailHelmet";
        case 303: return (const char*)"ChainmailChestplate";
        case 304: return (const char*)"ChainmailLeggings";
        case 305: return (const char*)"ChainmailBoots";
        case 306: return (const char*)"IronHelmet";
        case 307: return (const char*)"IronChestplate";
        case 308: return (const char*)"IronLeggings";
        case 309: return (const char*)"IronBoots";
        case 310: return (const char*)"DiamondHelmet";
        case 311: return (const char*)"DiamondChestplate";
        case 312: return (const char*)"DiamondLeggings";
        case 313: return (const char*)"DiamondBoots";
        case 314: return (const char*)"GoldHelmet";
        case 315: return (const char*)"GoldChestplate";
        case 316: return (const char*)"GoldLeggings";
        case 317: return (const char*)"GoldBoots";
        case 318: return (const char*)"Flint";
        case 319: return (const char*)"RawPorkchop";
        case 320: return (const char*)"CookedPorkchop";
        case 321: return (const char*)"Painting";
        case 322: return (const char*)"GoldenApple";
        case 323: return (const char*)"Sign";
        case 324: return (const char*)"WoodenDoor";
        case 325: return (const char*)"Bucket";
        case 326: return (const char*)"WaterBucket";
        case 327: return (const char*)"LavaBucket";
        case 328: return (const char*)"Minecart";
        case 329: return (const char*)"Saddle";
        case 330: return (const char*)"IronDoor";
        case 331: return (const char*)"Redstone";
        case 332: return (const char*)"Snowball";
        case 333: return (const char*)"Boat";
        case 334: return (const char*)"Leather";
        case 335: return (const char*)"MilkBucket";
        case 336: return (const char*)"ClayBrick";
        case 337: return (const char*)"ClayBall";
        case 338: return (const char*)"SugarCane";
        case 339: return (const char*)"Paper";
        case 340: return (const char*)"Book";
        case 341: return (const char*)"Slimeball";
        case 342: return (const char*)"StorageMinecart";
        case 343: return (const char*)"PoweredMinecart";
        case 344: return (const char*)"Egg";
        case 345: return (const char*)"Compass";
        case 346: return (const char*)"FishingRod";
        case 347: return (const char*)"Clock";
        case 348: return (const char*)"GlowstoneDust";
        case 349: return (const char*)"RawFish";
        case 350: return (const char*)"CookedFish";
        case 351: return (const char*)"InkSac";
        case 352: return (const char*)"Bone";
        case 353: return (const char*)"Sugar";
        case 354: return (const char*)"Cake";
        case 355: return (const char*)"Bed";
        case 356: return (const char*)"RedstoneRepeater";
        case 357: return (const char*)"Cookie";
        case 358: return (const char*)"Map";
        case 359: return (const char*)"Shears";
        case 2256: return (const char*)"GoldMusicDisc";
        case 2257: return (const char*)"GreenMusicDisc";
    }
}

inline int item_maxstack(int id) {
    switch(id) {
        case -1: return false;
        case 0: return false;
        case 1: return false;
        case 2: return false;
        case 3: return false;
        case 4: return false;
        case 5: return false;
        case 6: return false;
        case 7: return false;
        case 8: return false;
        case 9: return false;
        case 10: return false;
        case 11: return false;
        case 12: return false;
        case 13: return false;
        case 14: return false;
        case 15: return false;
        case 16: return false;
        case 17: return false;
        case 18: return false;
        case 19: return false;
        case 20: return false;
        case 21: return false;
        case 22: return false;
        case 23: return false;
        case 24: return false;
        case 25: return false;
        case 26: return true;
        case 27: return false;
        case 28: return false;
        case 29: return false;
        case 30: return false;
        case 31: return false;
        case 32: return false;
        case 33: return false;
        case 34: return false;
        case 35: return false;
        case 37: return false;
        case 38: return false;
        case 39: return false;
        case 40: return false;
        case 41: return false;
        case 42: return false;
        case 43: return false;
        case 44: return false;
        case 45: return false;
        case 46: return false;
        case 47: return false;
        case 48: return false;
        case 49: return false;
        case 50: return false;
        case 51: return false;
        case 52: return false;
        case 53: return false;
        case 54: return false;
        case 55: return false;
        case 56: return false;
        case 57: return false;
        case 58: return false;
        case 59: return false;
        case 60: return false;
        case 61: return false;
        case 62: return false;
        case 63: return true;
        case 64: return true;
        case 65: return false;
        case 66: return false;
        case 67: return false;
        case 68: return true;
        case 69: return false;
        case 70: return false;
        case 71: return true;
        case 72: return false;
        case 73: return false;
        case 74: return false;
        case 75: return false;
        case 76: return false;
        case 77: return false;
        case 78: return false;
        case 79: return false;
        case 80: return false;
        case 81: return false;
        case 82: return false;
        case 83: return false;
        case 84: return false;
        case 85: return false;
        case 86: return false;
        case 87: return false;
        case 88: return false;
        case 89: return false;
        case 90: return false;
        case 91: return false;
        case 92: return true;
        case 93: return false;
        case 94: return false;
        case 96: return false;
        case 256: return true;
        case 257: return true;
        case 258: return true;
        case 259: return true;
        case 260: return true;
        case 261: return true;
        case 262: return false;
        case 263: return false;
        case 264: return false;
        case 265: return false;
        case 266: return false;
        case 267: return true;
        case 268: return true;
        case 269: return true;
        case 270: return true;
        case 271: return true;
        case 272: return true;
        case 273: return true;
        case 274: return true;
        case 275: return true;
        case 276: return true;
        case 277: return true;
        case 278: return true;
        case 279: return true;
        case 280: return false;
        case 281: return false;
        case 282: return true;
        case 283: return true;
        case 284: return true;
        case 285: return true;
        case 286: return true;
        case 287: return false;
        case 288: return false;
        case 289: return false;
        case 290: return true;
        case 291: return true;
        case 292: return true;
        case 293: return true;
        case 294: return true;
        case 295: return false;
        case 296: return false;
        case 297: return true;
        case 298: return true;
        case 299: return true;
        case 300: return true;
        case 301: return true;
        case 302: return true;
        case 303: return true;
        case 304: return true;
        case 305: return true;
        case 306: return true;
        case 307: return true;
        case 308: return true;
        case 309: return true;
        case 310: return true;
        case 311: return true;
        case 312: return true;
        case 313: return true;
        case 314: return true;
        case 315: return true;
        case 316: return true;
        case 317: return true;
        case 318: return false;
        case 319: return true;
        case 320: return true;
        case 321: return false;
        case 322: return true;
        case 323: return true;
        case 324: return true;
        case 325: return true;
        case 326: return true;
        case 327: return true;
        case 328: return true;
        case 329: return true;
        case 330: return true;
        case 331: return false;
        case 332: return false;
        case 333: return true;
        case 334: return false;
        case 335: return true;
        case 336: return false;
        case 337: return false;
        case 338: return false;
        case 339: return false;
        case 340: return false;
        case 341: return false;
        case 342: return true;
        case 343: return true;
        case 344: return false;
        case 345: return false;
        case 346: return false;
        case 347: return false;
        case 348: return false;
        case 349: return true;
        case 350: return true;
        case 351: return false;
        case 352: return false;
        case 353: return false;
        case 354: return true;
        case 355: return true;
        case 356: return false;
        case 357: return false;
        case 358: return true;
        case 359: return true;
        case 2256: return true;
        case 2257: return true;
    }
}

inline bool item_placeable(int id) {
    switch(id) {
        case -1: return true;
        case 0: return true;
        case 1: return true;
        case 2: return true;
        case 3: return true;
        case 4: return true;
        case 5: return true;
        case 6: return true;
        case 7: return true;
        case 8: return true;
        case 9: return true;
        case 10: return true;
        case 11: return true;
        case 12: return true;
        case 13: return true;
        case 14: return true;
        case 15: return true;
        case 16: return true;
        case 17: return true;
        case 18: return true;
        case 19: return true;
        case 20: return true;
        case 21: return true;
        case 22: return true;
        case 23: return true;
        case 24: return true;
        case 25: return true;
        case 26: return true;
        case 27: return true;
        case 28: return true;
        case 29: return true;
        case 30: return true;
        case 31: return true;
        case 32: return true;
        case 33: return true;
        case 34: return true;
        case 35: return true;
        case 37: return true;
        case 38: return true;
        case 39: return true;
        case 40: return true;
        case 41: return true;
        case 42: return true;
        case 43: return true;
        case 44: return true;
        case 45: return true;
        case 46: return true;
        case 47: return true;
        case 48: return true;
        case 49: return true;
        case 50: return true;
        case 51: return true;
        case 52: return true;
        case 53: return true;
        case 54: return true;
        case 55: return true;
        case 56: return true;
        case 57: return true;
        case 58: return true;
        case 59: return true;
        case 60: return true;
        case 61: return true;
        case 62: return true;
        case 63: return true;
        case 64: return true;
        case 65: return true;
        case 66: return true;
        case 67: return true;
        case 68: return true;
        case 69: return true;
        case 70: return true;
        case 71: return true;
        case 72: return true;
        case 73: return true;
        case 74: return true;
        case 75: return true;
        case 76: return true;
        case 77: return true;
        case 78: return true;
        case 79: return true;
        case 80: return true;
        case 81: return true;
        case 82: return true;
        case 83: return true;
        case 84: return true;
        case 85: return true;
        case 86: return true;
        case 87: return true;
        case 88: return true;
        case 89: return true;
        case 90: return true;
        case 91: return true;
        case 92: return true;
        case 93: return true;
        case 94: return true;
        case 96: return true;
        case 256: return false;
        case 257: return false;
        case 258: return false;
        case 259: return false;
        case 260: return false;
        case 261: return false;
        case 262: return false;
        case 263: return false;
        case 264: return false;
        case 265: return false;
        case 266: return false;
        case 267: return false;
        case 268: return false;
        case 269: return false;
        case 270: return false;
        case 271: return false;
        case 272: return false;
        case 273: return false;
        case 274: return false;
        case 275: return false;
        case 276: return false;
        case 277: return false;
        case 278: return false;
        case 279: return false;
        case 280: return false;
        case 281: return false;
        case 282: return false;
        case 283: return false;
        case 284: return false;
        case 285: return false;
        case 286: return false;
        case 287: return false;
        case 288: return false;
        case 289: return false;
        case 290: return true;
        case 291: return true;
        case 292: return true;
        case 293: return true;
        case 294: return true;
        case 295: return true;
        case 296: return false;
        case 297: return false;
        case 298: return false;
        case 299: return false;
        case 300: return false;
        case 301: return false;
        case 302: return false;
        case 303: return false;
        case 304: return false;
        case 305: return false;
        case 306: return false;
        case 307: return false;
        case 308: return false;
        case 309: return false;
        case 310: return false;
        case 311: return false;
        case 312: return false;
        case 313: return false;
        case 314: return false;
        case 315: return false;
        case 316: return false;
        case 317: return false;
        case 318: return false;
        case 319: return false;
        case 320: return false;
        case 321: return true;
        case 322: return false;
        case 323: return true;
        case 324: return true;
        case 325: return true;
        case 326: return true;
        case 327: return true;
        case 328: return true;
        case 329: return true;
        case 330: return true;
        case 331: return true;
        case 332: return false;
        case 333: return true;
        case 334: return false;
        case 335: return true;
        case 336: return false;
        case 337: return false;
        case 338: return false;
        case 339: return false;
        case 340: return false;
        case 341: return false;
        case 342: return true;
        case 343: return true;
        case 344: return false;
        case 345: return false;
        case 346: return false;
        case 347: return false;
        case 348: return false;
        case 349: return false;
        case 350: return false;
        case 351: return true;
        case 352: return false;
        case 353: return false;
        case 354: return true;
        case 355: return true;
        case 356: return true;
        case 357: return true;
        case 358: return true;
        case 359: return true;
        case 2256: return true;
        case 2257: return true;
    }
}

inline bool item_usable(int id) {
    switch(id) {
        case -1: return false;
        case 0: return false;
        case 1: return false;
        case 2: return false;
        case 3: return false;
        case 4: return false;
        case 5: return false;
        case 6: return false;
        case 7: return false;
        case 8: return false;
        case 9: return false;
        case 10: return false;
        case 11: return false;
        case 12: return false;
        case 13: return false;
        case 14: return false;
        case 15: return false;
        case 16: return false;
        case 17: return false;
        case 18: return false;
        case 19: return false;
        case 20: return false;
        case 21: return false;
        case 22: return false;
        case 23: return false;
        case 24: return false;
        case 25: return false;
        case 26: return false;
        case 27: return false;
        case 28: return false;
        case 29: return false;
        case 30: return false;
        case 31: return false;
        case 32: return false;
        case 33: return false;
        case 34: return false;
        case 35: return false;
        case 37: return false;
        case 38: return false;
        case 39: return false;
        case 40: return false;
        case 41: return false;
        case 42: return false;
        case 43: return false;
        case 44: return false;
        case 45: return false;
        case 46: return false;
        case 47: return false;
        case 48: return false;
        case 49: return false;
        case 50: return false;
        case 51: return false;
        case 52: return false;
        case 53: return false;
        case 54: return false;
        case 55: return false;
        case 56: return false;
        case 57: return false;
        case 58: return false;
        case 59: return false;
        case 60: return false;
        case 61: return false;
        case 62: return false;
        case 63: return false;
        case 64: return false;
        case 65: return false;
        case 66: return false;
        case 67: return false;
        case 68: return false;
        case 69: return false;
        case 70: return false;
        case 71: return false;
        case 72: return false;
        case 73: return false;
        case 74: return false;
        case 75: return false;
        case 76: return false;
        case 77: return false;
        case 78: return false;
        case 79: return false;
        case 80: return false;
        case 81: return false;
        case 82: return false;
        case 83: return false;
        case 84: return false;
        case 85: return false;
        case 86: return false;
        case 87: return false;
        case 88: return false;
        case 89: return false;
        case 90: return false;
        case 91: return false;
        case 92: return false;
        case 93: return false;
        case 94: return false;
        case 96: return false;
        case 256: return false;
        case 257: return false;
        case 258: return false;
        case 259: return false;
        case 260: return true;
        case 261: return true;
        case 262: return false;
        case 263: return false;
        case 264: return false;
        case 265: return false;
        case 266: return false;
        case 267: return false;
        case 268: return false;
        case 269: return false;
        case 270: return false;
        case 271: return false;
        case 272: return false;
        case 273: return false;
        case 274: return false;
        case 275: return false;
        case 276: return false;
        case 277: return false;
        case 278: return false;
        case 279: return false;
        case 280: return false;
        case 281: return false;
        case 282: return true;
        case 283: return false;
        case 284: return false;
        case 285: return false;
        case 286: return false;
        case 287: return false;
        case 288: return false;
        case 289: return false;
        case 290: return false;
        case 291: return false;
        case 292: return false;
        case 293: return false;
        case 294: return false;
        case 295: return false;
        case 296: return false;
        case 297: return true;
        case 298: return false;
        case 299: return false;
        case 300: return false;
        case 301: return false;
        case 302: return false;
        case 303: return false;
        case 304: return false;
        case 305: return false;
        case 306: return false;
        case 307: return false;
        case 308: return false;
        case 309: return false;
        case 310: return false;
        case 311: return false;
        case 312: return false;
        case 313: return false;
        case 314: return false;
        case 315: return false;
        case 316: return false;
        case 317: return false;
        case 318: return false;
        case 319: return true;
        case 320: return true;
        case 321: return false;
        case 322: return true;
        case 323: return false;
        case 324: return false;
        case 325: return false;
        case 326: return false;
        case 327: return false;
        case 328: return false;
        case 329: return false;
        case 330: return false;
        case 331: return false;
        case 332: return true;
        case 333: return false;
        case 334: return false;
        case 335: return false;
        case 336: return false;
        case 337: return false;
        case 338: return false;
        case 339: return false;
        case 340: return false;
        case 341: return false;
        case 342: return false;
        case 343: return false;
        case 344: return true;
        case 345: return false;
        case 346: return true;
        case 347: return false;
        case 348: return false;
        case 349: return true;
        case 350: return true;
        case 351: return false;
        case 352: return false;
        case 353: return false;
        case 354: return false;
        case 355: return false;
        case 356: return false;
        case 357: return false;
        case 358: return false;
        case 359: return false;
        case 2256: return false;
        case 2257: return false;
    }
}

inline bool item_passable(int id) {
    switch(id) {
        case -1: return true;
        case 0: return true;
        case 1: return false;
        case 2: return false;
        case 3: return false;
        case 4: return false;
        case 5: return false;
        case 6: return true;
        case 7: return false;
        case 8: return true;
        case 9: return true;
        case 10: return true;
        case 11: return true;
        case 12: return false;
        case 13: return false;
        case 14: return false;
        case 15: return false;
        case 16: return false;
        case 17: return false;
        case 18: return false;
        case 19: return false;
        case 20: return false;
        case 21: return false;
        case 22: return false;
        case 23: return false;
        case 24: return false;
        case 25: return false;
        case 26: return false;
        case 27: return true;
        case 28: return true;
        case 29: return true;
        case 30: return false;
        case 31: return true;
        case 32: return true;
        case 33: return true;
        case 34: return true;
        case 35: return false;
        case 37: return true;
        case 38: return true;
        case 39: return true;
        case 40: return true;
        case 41: return false;
        case 42: return false;
        case 43: return false;
        case 44: return false;
        case 45: return false;
        case 46: return false;
        case 47: return false;
        case 48: return false;
        case 49: return false;
        case 50: return true;
        case 51: return true;
        case 52: return false;
        case 53: return false;
        case 54: return false;
        case 55: return true;
        case 56: return false;
        case 57: return false;
        case 58: return false;
        case 59: return true;
        case 60: return false;
        case 61: return false;
        case 62: return false;
        case 63: return true;
        case 64: return false;
        case 65: return false;
        case 66: return true;
        case 67: return false;
        case 68: return true;
        case 69: return true;
        case 70: return true;
        case 71: return false;
        case 72: return true;
        case 73: return false;
        case 74: return false;
        case 75: return true;
        case 76: return true;
        case 77: return true;
        case 78: return true;
        case 79: return false;
        case 80: return false;
        case 81: return false;
        case 82: return false;
        case 83: return true;
        case 84: return false;
        case 85: return false;
        case 86: return false;
        case 87: return false;
        case 88: return false;
        case 89: return false;
        case 90: return true;
        case 91: return false;
        case 92: return false;
        case 93: return false;
        case 94: return false;
        case 96: return false;
        case 256: return true;
        case 257: return true;
        case 258: return true;
        case 259: return true;
        case 260: return true;
        case 261: return true;
        case 262: return true;
        case 263: return true;
        case 264: return true;
        case 265: return true;
        case 266: return true;
        case 267: return true;
        case 268: return true;
        case 269: return true;
        case 270: return true;
        case 271: return true;
        case 272: return true;
        case 273: return true;
        case 274: return true;
        case 275: return true;
        case 276: return true;
        case 277: return true;
        case 278: return true;
        case 279: return true;
        case 280: return true;
        case 281: return true;
        case 282: return true;
        case 283: return true;
        case 284: return true;
        case 285: return true;
        case 286: return true;
        case 287: return true;
        case 288: return true;
        case 289: return true;
        case 290: return true;
        case 291: return true;
        case 292: return true;
        case 293: return true;
        case 294: return true;
        case 295: return true;
        case 296: return true;
        case 297: return true;
        case 298: return true;
        case 299: return true;
        case 300: return true;
        case 301: return true;
        case 302: return true;
        case 303: return true;
        case 304: return true;
        case 305: return true;
        case 306: return true;
        case 307: return true;
        case 308: return true;
        case 309: return true;
        case 310: return true;
        case 311: return true;
        case 312: return true;
        case 313: return true;
        case 314: return true;
        case 315: return true;
        case 316: return true;
        case 317: return true;
        case 318: return true;
        case 319: return true;
        case 320: return true;
        case 321: return true;
        case 322: return true;
        case 323: return true;
        case 324: return true;
        case 325: return true;
        case 326: return true;
        case 327: return true;
        case 328: return true;
        case 329: return true;
        case 330: return true;
        case 331: return true;
        case 332: return true;
        case 333: return true;
        case 334: return true;
        case 335: return true;
        case 336: return true;
        case 337: return true;
        case 338: return true;
        case 339: return true;
        case 340: return true;
        case 341: return true;
        case 342: return true;
        case 343: return true;
        case 344: return true;
        case 345: return true;
        case 346: return true;
        case 347: return true;
        case 348: return true;
        case 349: return true;
        case 350: return true;
        case 351: return true;
        case 352: return true;
        case 353: return true;
        case 354: return true;
        case 355: return true;
        case 356: return true;
        case 357: return true;
        case 358: return true;
        case 359: return true;
        case 2256: return true;
        case 2257: return true;
    }
}

inline bool item_diggable(int id) {
    switch(id) {
        case -1: return false;
        case 0: return false;
        case 1: return true;
        case 2: return true;
        case 3: return true;
        case 4: return true;
        case 5: return true;
        case 6: return true;
        case 7: return true;
        case 8: return false;
        case 9: return false;
        case 10: return false;
        case 11: return false;
        case 12: return true;
        case 13: return true;
        case 14: return true;
        case 15: return true;
        case 16: return true;
        case 17: return true;
        case 18: return true;
        case 19: return true;
        case 20: return true;
        case 21: return true;
        case 22: return true;
        case 23: return true;
        case 24: return true;
        case 25: return true;
        case 26: return true;
        case 27: return true;
        case 28: return true;
        case 29: return true;
        case 30: return true;
        case 31: return true;
        case 32: return true;
        case 33: return true;
        case 34: return true;
        case 35: return true;
        case 37: return true;
        case 38: return true;
        case 39: return true;
        case 40: return true;
        case 41: return true;
        case 42: return true;
        case 43: return true;
        case 44: return true;
        case 45: return true;
        case 46: return true;
        case 47: return true;
        case 48: return true;
        case 49: return true;
        case 50: return true;
        case 51: return false;
        case 52: return true;
        case 53: return true;
        case 54: return true;
        case 55: return true;
        case 56: return true;
        case 57: return true;
        case 58: return true;
        case 59: return true;
        case 60: return true;
        case 61: return true;
        case 62: return true;
        case 63: return true;
        case 64: return true;
        case 65: return true;
        case 66: return true;
        case 67: return true;
        case 68: return true;
        case 69: return true;
        case 70: return true;
        case 71: return true;
        case 72: return true;
        case 73: return true;
        case 74: return true;
        case 75: return true;
        case 76: return true;
        case 77: return true;
        case 78: return true;
        case 79: return true;
        case 80: return true;
        case 81: return true;
        case 82: return true;
        case 83: return true;
        case 84: return true;
        case 85: return true;
        case 86: return true;
        case 87: return true;
        case 88: return true;
        case 89: return true;
        case 90: return true;
        case 91: return true;
        case 92: return true;
        case 93: return true;
        case 94: return true;
        case 96: return true;
        case 256: return true;
        case 257: return true;
        case 258: return true;
        case 259: return true;
        case 260: return true;
        case 261: return true;
        case 262: return true;
        case 263: return true;
        case 264: return true;
        case 265: return true;
        case 266: return true;
        case 267: return true;
        case 268: return true;
        case 269: return true;
        case 270: return true;
        case 271: return true;
        case 272: return true;
        case 273: return true;
        case 274: return true;
        case 275: return true;
        case 276: return true;
        case 277: return true;
        case 278: return true;
        case 279: return true;
        case 280: return true;
        case 281: return true;
        case 282: return true;
        case 283: return true;
        case 284: return true;
        case 285: return true;
        case 286: return true;
        case 287: return true;
        case 288: return true;
        case 289: return true;
        case 290: return true;
        case 291: return true;
        case 292: return true;
        case 293: return true;
        case 294: return true;
        case 295: return true;
        case 296: return true;
        case 297: return true;
        case 298: return true;
        case 299: return true;
        case 300: return true;
        case 301: return true;
        case 302: return true;
        case 303: return true;
        case 304: return true;
        case 305: return true;
        case 306: return true;
        case 307: return true;
        case 308: return true;
        case 309: return true;
        case 310: return true;
        case 311: return true;
        case 312: return true;
        case 313: return true;
        case 314: return true;
        case 315: return true;
        case 316: return true;
        case 317: return true;
        case 318: return true;
        case 319: return true;
        case 320: return true;
        case 321: return true;
        case 322: return true;
        case 323: return true;
        case 324: return true;
        case 325: return true;
        case 326: return true;
        case 327: return true;
        case 328: return true;
        case 329: return true;
        case 330: return true;
        case 331: return true;
        case 332: return true;
        case 333: return true;
        case 334: return true;
        case 335: return true;
        case 336: return true;
        case 337: return true;
        case 338: return true;
        case 339: return true;
        case 340: return true;
        case 341: return true;
        case 342: return true;
        case 343: return true;
        case 344: return true;
        case 345: return true;
        case 346: return true;
        case 347: return true;
        case 348: return true;
        case 349: return true;
        case 350: return true;
        case 351: return true;
        case 352: return true;
        case 353: return true;
        case 354: return true;
        case 355: return true;
        case 356: return true;
        case 357: return true;
        case 358: return true;
        case 359: return true;
        case 2256: return true;
        case 2257: return true;
    }
}

inline bool item_activatable(int id) {
    switch(id) {
        case -1: return false;
        case 0: return false;
        case 1: return false;
        case 2: return false;
        case 3: return false;
        case 4: return false;
        case 5: return false;
        case 6: return false;
        case 7: return false;
        case 8: return false;
        case 9: return false;
        case 10: return false;
        case 11: return false;
        case 12: return false;
        case 13: return false;
        case 14: return false;
        case 15: return false;
        case 16: return false;
        case 17: return false;
        case 18: return false;
        case 19: return false;
        case 20: return false;
        case 21: return false;
        case 22: return false;
        case 23: return true;
        case 24: return false;
        case 25: return true;
        case 26: return true;
        case 27: return false;
        case 28: return false;
        case 29: return false;
        case 30: return false;
        case 31: return false;
        case 32: return false;
        case 33: return false;
        case 34: return false;
        case 35: return false;
        case 37: return false;
        case 38: return false;
        case 39: return false;
        case 40: return false;
        case 41: return false;
        case 42: return false;
        case 43: return false;
        case 44: return false;
        case 45: return false;
        case 46: return false;
        case 47: return false;
        case 48: return false;
        case 49: return false;
        case 50: return false;
        case 51: return false;
        case 52: return false;
        case 53: return false;
        case 54: return true;
        case 55: return false;
        case 56: return false;
        case 57: return false;
        case 58: return true;
        case 59: return false;
        case 60: return false;
        case 61: return true;
        case 62: return true;
        case 63: return false;
        case 64: return true;
        case 65: return false;
        case 66: return false;
        case 67: return false;
        case 68: return false;
        case 69: return true;
        case 70: return false;
        case 71: return true;
        case 72: return false;
        case 73: return false;
        case 74: return false;
        case 75: return false;
        case 76: return false;
        case 77: return true;
        case 78: return false;
        case 79: return false;
        case 80: return false;
        case 81: return false;
        case 82: return false;
        case 83: return false;
        case 84: return false;
        case 85: return false;
        case 86: return false;
        case 87: return false;
        case 88: return false;
        case 89: return false;
        case 90: return false;
        case 91: return false;
        case 92: return true;
        case 93: return true;
        case 94: return true;
        case 96: return true;
        case 256: return false;
        case 257: return false;
        case 258: return false;
        case 259: return false;
        case 260: return false;
        case 261: return false;
        case 262: return false;
        case 263: return false;
        case 264: return false;
        case 265: return false;
        case 266: return false;
        case 267: return false;
        case 268: return false;
        case 269: return false;
        case 270: return false;
        case 271: return false;
        case 272: return false;
        case 273: return false;
        case 274: return false;
        case 275: return false;
        case 276: return false;
        case 277: return false;
        case 278: return false;
        case 279: return false;
        case 280: return false;
        case 281: return false;
        case 282: return false;
        case 283: return false;
        case 284: return false;
        case 285: return false;
        case 286: return false;
        case 287: return false;
        case 288: return false;
        case 289: return false;
        case 290: return false;
        case 291: return false;
        case 292: return false;
        case 293: return false;
        case 294: return false;
        case 295: return false;
        case 296: return false;
        case 297: return false;
        case 298: return false;
        case 299: return false;
        case 300: return false;
        case 301: return false;
        case 302: return false;
        case 303: return false;
        case 304: return false;
        case 305: return false;
        case 306: return false;
        case 307: return false;
        case 308: return false;
        case 309: return false;
        case 310: return false;
        case 311: return false;
        case 312: return false;
        case 313: return false;
        case 314: return false;
        case 315: return false;
        case 316: return false;
        case 317: return false;
        case 318: return false;
        case 319: return false;
        case 320: return false;
        case 321: return false;
        case 322: return false;
        case 323: return false;
        case 324: return false;
        case 325: return false;
        case 326: return false;
        case 327: return false;
        case 328: return false;
        case 329: return false;
        case 330: return false;
        case 331: return false;
        case 332: return false;
        case 333: return false;
        case 334: return false;
        case 335: return false;
        case 336: return false;
        case 337: return false;
        case 338: return false;
        case 339: return false;
        case 340: return false;
        case 341: return false;
        case 342: return false;
        case 343: return false;
        case 344: return false;
        case 345: return false;
        case 346: return false;
        case 347: return false;
        case 348: return false;
        case 349: return false;
        case 350: return false;
        case 351: return false;
        case 352: return false;
        case 353: return false;
        case 354: return false;
        case 355: return false;
        case 356: return false;
        case 357: return false;
        case 358: return false;
        case 359: return false;
        case 2256: return false;
        case 2257: return false;
    }
}

inline bool item_safe(int id) {
    switch(id) {
        case -1: return true;
        case 0: return true;
        case 1: return false;
        case 2: return false;
        case 3: return false;
        case 4: return false;
        case 5: return false;
        case 6: return true;
        case 7: return false;
        case 8: return true;
        case 9: return true;
        case 10: return false;
        case 11: return false;
        case 12: return false;
        case 13: return false;
        case 14: return false;
        case 15: return false;
        case 16: return false;
        case 17: return false;
        case 18: return false;
        case 19: return false;
        case 20: return false;
        case 21: return false;
        case 22: return false;
        case 23: return false;
        case 24: return false;
        case 25: return false;
        case 26: return false;
        case 27: return true;
        case 28: return true;
        case 29: return true;
        case 30: return false;
        case 31: return true;
        case 32: return true;
        case 33: return true;
        case 34: return true;
        case 35: return false;
        case 37: return true;
        case 38: return true;
        case 39: return true;
        case 40: return true;
        case 41: return false;
        case 42: return false;
        case 43: return false;
        case 44: return false;
        case 45: return false;
        case 46: return false;
        case 47: return false;
        case 48: return false;
        case 49: return false;
        case 50: return true;
        case 51: return false;
        case 52: return false;
        case 53: return false;
        case 54: return false;
        case 55: return true;
        case 56: return false;
        case 57: return false;
        case 58: return false;
        case 59: return false;
        case 60: return false;
        case 61: return false;
        case 62: return false;
        case 63: return true;
        case 64: return false;
        case 65: return false;
        case 66: return true;
        case 67: return false;
        case 68: return true;
        case 69: return true;
        case 70: return true;
        case 71: return false;
        case 72: return true;
        case 73: return false;
        case 74: return false;
        case 75: return true;
        case 76: return true;
        case 77: return true;
        case 78: return true;
        case 79: return false;
        case 80: return false;
        case 81: return false;
        case 82: return false;
        case 83: return true;
        case 84: return false;
        case 85: return false;
        case 86: return false;
        case 87: return false;
        case 88: return false;
        case 89: return false;
        case 90: return true;
        case 91: return false;
        case 92: return false;
        case 93: return false;
        case 94: return false;
        case 96: return false;
        case 256: return true;
        case 257: return true;
        case 258: return true;
        case 259: return true;
        case 260: return true;
        case 261: return true;
        case 262: return true;
        case 263: return true;
        case 264: return true;
        case 265: return true;
        case 266: return true;
        case 267: return true;
        case 268: return true;
        case 269: return true;
        case 270: return true;
        case 271: return true;
        case 272: return true;
        case 273: return true;
        case 274: return true;
        case 275: return true;
        case 276: return true;
        case 277: return true;
        case 278: return true;
        case 279: return true;
        case 280: return true;
        case 281: return true;
        case 282: return true;
        case 283: return true;
        case 284: return true;
        case 285: return true;
        case 286: return true;
        case 287: return true;
        case 288: return true;
        case 289: return true;
        case 290: return true;
        case 291: return true;
        case 292: return true;
        case 293: return true;
        case 294: return true;
        case 295: return true;
        case 296: return true;
        case 297: return true;
        case 298: return true;
        case 299: return true;
        case 300: return true;
        case 301: return true;
        case 302: return true;
        case 303: return true;
        case 304: return true;
        case 305: return true;
        case 306: return true;
        case 307: return true;
        case 308: return true;
        case 309: return true;
        case 310: return true;
        case 311: return true;
        case 312: return true;
        case 313: return true;
        case 314: return true;
        case 315: return true;
        case 316: return true;
        case 317: return true;
        case 318: return true;
        case 319: return true;
        case 320: return true;
        case 321: return true;
        case 322: return true;
        case 323: return true;
        case 324: return true;
        case 325: return true;
        case 326: return true;
        case 327: return true;
        case 328: return true;
        case 329: return true;
        case 330: return true;
        case 331: return true;
        case 332: return true;
        case 333: return true;
        case 334: return true;
        case 335: return true;
        case 336: return true;
        case 337: return true;
        case 338: return true;
        case 339: return true;
        case 340: return true;
        case 341: return true;
        case 342: return true;
        case 343: return true;
        case 344: return true;
        case 345: return true;
        case 346: return true;
        case 347: return true;
        case 348: return true;
        case 349: return true;
        case 350: return true;
        case 351: return true;
        case 352: return true;
        case 353: return true;
        case 354: return true;
        case 355: return true;
        case 356: return true;
        case 357: return true;
        case 358: return true;
        case 359: return true;
        case 2256: return true;
        case 2257: return true;
    }
}

inline float item_hardness(int id) {
    switch(id) {
        case -1: return 0;
        case 0: return 0;
        case 1: return 1.5;
        case 2: return 0.6;
        case 3: return 0.5;
        case 4: return 2.0;
        case 5: return 2.0;
        case 6: return 0.0;
        case 7: return -1;
        case 8: return 100;
        case 9: return 100;
        case 10: return 100;
        case 11: return 0.0;
        case 12: return 0.5;
        case 13: return 0.6;
        case 14: return 3;
        case 15: return 3;
        case 16: return 3;
        case 17: return 2.0;
        case 18: return 0.2;
        case 19: return 0.6;
        case 20: return 0.3;
        case 21: return 3;
        case 22: return 3;
        case 23: return 3.5;
        case 24: return 0.8;
        case 25: return 0.8;
        case 26: return 0.2;
        case 27: return 0.7;
        case 28: return 0.7;
        case 29: return 1;
        case 30: return 0;
        case 31: return 0;
        case 32: return 0;
        case 33: return 1;
        case 34: return 1;
        case 35: return 0.8;
        case 37: return 0.0;
        case 38: return 0.0;
        case 39: return 0.0;
        case 40: return 0.0;
        case 41: return 3;
        case 42: return 5;
        case 43: return 2.0;
        case 44: return 2.0;
        case 45: return 2.0;
        case 46: return 0.0;
        case 47: return 1.5;
        case 48: return 2.0;
        case 49: return 10;
        case 50: return 0.0;
        case 51: return 0.0;
        case 52: return 5;
        case 53: return 2.0;
        case 54: return 2.5;
        case 55: return 0.0;
        case 56: return 3;
        case 57: return 5;
        case 58: return 2.5;
        case 59: return 0.0;
        case 60: return 0.6;
        case 61: return 3.5;
        case 62: return 3.5;
        case 63: return 1.0;
        case 64: return 3;
        case 65: return 0.4;
        case 66: return 0.7;
        case 67: return 2.0;
        case 68: return 1.0;
        case 69: return 0.5;
        case 70: return 0.5;
        case 71: return 5;
        case 72: return 0.5;
        case 73: return 3;
        case 74: return 3;
        case 75: return 0.0;
        case 76: return 0.0;
        case 77: return 0.5;
        case 78: return 0.1;
        case 79: return 0.5;
        case 80: return 0.2;
        case 81: return 0.4;
        case 82: return 0.6;
        case 83: return 0.0;
        case 84: return 2.0;
        case 85: return 2.0;
        case 86: return 1.0;
        case 87: return 0.4;
        case 88: return 0.5;
        case 89: return 0.3;
        case 90: return -1;
        case 91: return 1.0;
        case 92: return 0.5;
        case 93: return 0.0;
        case 94: return 0.0;
        case 96: return 3;
        case 256: return 0;
        case 257: return 0;
        case 258: return 0;
        case 259: return 0;
        case 260: return 0;
        case 261: return 0;
        case 262: return 0;
        case 263: return 0;
        case 264: return 0;
        case 265: return 0;
        case 266: return 0;
        case 267: return 0;
        case 268: return 0;
        case 269: return 0;
        case 270: return 0;
        case 271: return 0;
        case 272: return 0;
        case 273: return 0;
        case 274: return 0;
        case 275: return 0;
        case 276: return 0;
        case 277: return 0;
        case 278: return 0;
        case 279: return 0;
        case 280: return 0;
        case 281: return 0;
        case 282: return 0;
        case 283: return 0;
        case 284: return 0;
        case 285: return 0;
        case 286: return 0;
        case 287: return 0;
        case 288: return 0;
        case 289: return 0;
        case 290: return 0;
        case 291: return 0;
        case 292: return 0;
        case 293: return 0;
        case 294: return 0;
        case 295: return 0;
        case 296: return 0;
        case 297: return 0;
        case 298: return 0;
        case 299: return 0;
        case 300: return 0;
        case 301: return 0;
        case 302: return 0;
        case 303: return 0;
        case 304: return 0;
        case 305: return 0;
        case 306: return 0;
        case 307: return 0;
        case 308: return 0;
        case 309: return 0;
        case 310: return 0;
        case 311: return 0;
        case 312: return 0;
        case 313: return 0;
        case 314: return 0;
        case 315: return 0;
        case 316: return 0;
        case 317: return 0;
        case 318: return 0;
        case 319: return 0;
        case 320: return 0;
        case 321: return 0;
        case 322: return 0;
        case 323: return 0;
        case 324: return 0;
        case 325: return 0;
        case 326: return 0;
        case 327: return 0;
        case 328: return 0;
        case 329: return 0;
        case 330: return 0;
        case 331: return 0;
        case 332: return 0;
        case 333: return 0;
        case 334: return 0;
        case 335: return 0;
        case 336: return 0;
        case 337: return 0;
        case 338: return 0;
        case 339: return 0;
        case 340: return 0;
        case 341: return 0;
        case 342: return 0;
        case 343: return 0;
        case 344: return 0;
        case 345: return 0;
        case 346: return 0;
        case 347: return 0;
        case 348: return 0;
        case 349: return 0;
        case 350: return 0;
        case 351: return 0;
        case 352: return 0;
        case 353: return 0;
        case 354: return 0;
        case 355: return 0;
        case 356: return 0;
        case 357: return 0;
        case 358: return 0;
        case 359: return 0;
        case 2256: return 0;
        case 2257: return 0;
    }
}

inline int item_material(int id) {
    switch(id) {
        case -1: return M_NONE;
        case 0: return M_NONE;
        case 1: return M_STONE;
        case 2: return M_DIRT;
        case 3: return M_DIRT;
        case 4: return M_STONE;
        case 5: return M_WOOD;
        case 6: return M_CROPS;
        case 7: return M_STONE;
        case 8: return M_WATER;
        case 9: return M_WATER;
        case 10: return M_LAVA;
        case 11: return M_LAVA;
        case 12: return M_SAND;
        case 13: return M_SAND;
        case 14: return M_STONE;
        case 15: return M_STONE;
        case 16: return M_STONE;
        case 17: return M_WOOD;
        case 18: return M_LEAVES;
        case 19: return M_SPONGE;
        case 20: return M_GLASS;
        case 21: return M_STONE;
        case 22: return M_STONE;
        case 23: return M_STONE;
        case 24: return M_STONE;
        case 25: return M_WOOD;
        case 26: return M_WOOL;
        case 27: return M_REDSTONE;
        case 28: return M_REDSTONE;
        case 29: return M_STONE;
        case 30: return M_WOOL;
        case 31: return M_CROPS;
        case 32: return M_CROPS;
        case 33: return M_STONE;
        case 34: return M_STONE;
        case 35: return M_WOOL;
        case 37: return M_CROPS;
        case 38: return M_CROPS;
        case 39: return M_CROPS;
        case 40: return M_CROPS;
        case 41: return M_IRON;
        case 42: return M_IRON;
        case 43: return M_STONE;
        case 44: return M_STONE;
        case 45: return M_STONE;
        case 46: return M_TNT;
        case 47: return M_WOOD;
        case 48: return M_STONE;
        case 49: return M_STONE;
        case 50: return M_REDSTONE;
        case 51: return M_FIRE;
        case 52: return M_STONE;
        case 53: return M_WOOD;
        case 54: return M_WOOD;
        case 55: return M_REDSTONE;
        case 56: return M_STONE;
        case 57: return M_IRON;
        case 58: return M_WOOD;
        case 59: return M_CROPS;
        case 60: return M_DIRT;
        case 61: return M_STONE;
        case 62: return M_STONE;
        case 63: return M_WOOD;
        case 64: return M_WOOD;
        case 65: return M_REDSTONE;
        case 66: return M_REDSTONE;
        case 67: return M_STONE;
        case 68: return M_WOOD;
        case 69: return M_REDSTONE;
        case 70: return M_STONE;
        case 71: return M_IRON;
        case 72: return M_WOOD;
        case 73: return M_STONE;
        case 74: return M_STONE;
        case 75: return M_REDSTONE;
        case 76: return M_REDSTONE;
        case 77: return M_REDSTONE;
        case 78: return M_SNOW;
        case 79: return M_ICE;
        case 80: return M_SNOWBLOCK;
        case 81: return M_CACTUS;
        case 82: return M_CLAY;
        case 83: return M_CROPS;
        case 84: return M_WOOD;
        case 85: return M_WOOD;
        case 86: return M_PUMPKIN;
        case 87: return M_STONE;
        case 88: return M_SAND;
        case 89: return M_GLASS;
        case 90: return M_PORTAL;
        case 91: return M_PUMPKIN;
        case 92: return M_CAKE;
        case 93: return M_REDSTONE;
        case 94: return M_REDSTONE;
        case 96: return M_WOOD;
        case 256: return M_IRON;
        case 257: return M_IRON;
        case 258: return M_IRON;
        case 259: return M_NONE;
        case 260: return M_NONE;
        case 261: return M_NONE;
        case 262: return M_NONE;
        case 263: return M_NONE;
        case 264: return M_NONE;
        case 265: return M_NONE;
        case 266: return M_NONE;
        case 267: return M_IRON;
        case 268: return M_WOOD;
        case 269: return M_WOOD;
        case 270: return M_WOOD;
        case 271: return M_WOOD;
        case 272: return M_STONE;
        case 273: return M_STONE;
        case 274: return M_STONE;
        case 275: return M_STONE;
        case 276: return M_DIAMOND;
        case 277: return M_DIAMOND;
        case 278: return M_DIAMOND;
        case 279: return M_DIAMOND;
        case 280: return M_NONE;
        case 281: return M_NONE;
        case 282: return M_NONE;
        case 283: return M_GOLD;
        case 284: return M_GOLD;
        case 285: return M_GOLD;
        case 286: return M_GOLD;
        case 287: return M_NONE;
        case 288: return M_NONE;
        case 289: return M_NONE;
        case 290: return M_WOOD;
        case 291: return M_STONE;
        case 292: return M_IRON;
        case 293: return M_DIAMOND;
        case 294: return M_GOLD;
        case 295: return M_NONE;
        case 296: return M_NONE;
        case 297: return M_NONE;
        case 298: return M_NONE;
        case 299: return M_NONE;
        case 300: return M_NONE;
        case 301: return M_NONE;
        case 302: return M_NONE;
        case 303: return M_NONE;
        case 304: return M_NONE;
        case 305: return M_NONE;
        case 306: return M_NONE;
        case 307: return M_NONE;
        case 308: return M_NONE;
        case 309: return M_NONE;
        case 310: return M_NONE;
        case 311: return M_NONE;
        case 312: return M_NONE;
        case 313: return M_NONE;
        case 314: return M_NONE;
        case 315: return M_NONE;
        case 316: return M_NONE;
        case 317: return M_NONE;
        case 318: return M_NONE;
        case 319: return M_NONE;
        case 320: return M_NONE;
        case 321: return M_NONE;
        case 322: return M_NONE;
        case 323: return M_NONE;
        case 324: return M_NONE;
        case 325: return M_NONE;
        case 326: return M_NONE;
        case 327: return M_NONE;
        case 328: return M_NONE;
        case 329: return M_NONE;
        case 330: return M_NONE;
        case 331: return M_NONE;
        case 332: return M_NONE;
        case 333: return M_NONE;
        case 334: return M_NONE;
        case 335: return M_NONE;
        case 336: return M_NONE;
        case 337: return M_NONE;
        case 338: return M_NONE;
        case 339: return M_NONE;
        case 340: return M_NONE;
        case 341: return M_NONE;
        case 342: return M_NONE;
        case 343: return M_NONE;
        case 344: return M_NONE;
        case 345: return M_NONE;
        case 346: return M_NONE;
        case 347: return M_NONE;
        case 348: return M_NONE;
        case 349: return M_NONE;
        case 350: return M_NONE;
        case 351: return M_NONE;
        case 352: return M_NONE;
        case 353: return M_NONE;
        case 354: return M_NONE;
        case 355: return M_NONE;
        case 356: return M_NONE;
        case 357: return M_NONE;
        case 358: return M_NONE;
        case 359: return M_NONE;
        case 2256: return M_NONE;
        case 2257: return M_NONE;
    }
}

#endif


